{{- if eq (include "stalwart.provisioningEnabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stalwart.fullname" . }}-provisioning
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
data:
  plan.ndjson: |
    {{- include "stalwart.provisioningPlan" . | nindent 4 }}
{{- end }}
