{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stalwart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" (merge (omit .Values.serviceAccount.labels "app.kubernetes.io/name" "app.kubernetes.io/instance") (omit .Values.additionalLabels "app.kubernetes.io/name" "app.kubernetes.io/instance")) "context" .) | nindent 4 }}
  annotations:
    {{- include "stalwart.annotations" (dict "specific" .Values.serviceAccount.annotations "context" .) | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
