apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  annotations:
    {{- include "stalwart.annotations" (dict "specific" dict "context" .) | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: mgmt
      port: {{ include "stalwart.managementPort" . }}
      targetPort: mgmt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-management
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
  annotations:
    {{- include "stalwart.annotations" (dict "specific" .Values.management.annotations "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: mgmt
      port: {{ .Values.management.servicePort }}
      targetPort: mgmt
{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  annotations:
    {{- include "stalwart.annotations" (dict "specific" .Values.service.annotations "context" .) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - name: {{ $name }}
      port: {{ $port.port }}
      targetPort: {{ $name }}
      protocol: {{ $port.protocol }}
    {{- end }}
{{- end }}
