{{- if eq (include "stalwart.webmailNeedsManagedSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.webmailFullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.webmailLabels" . | nindent 4 }}
  annotations:
    {{- include "stalwart.webmailAnnotations" (dict "specific" dict "context" .) | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.webmail.sessionSecret.existingSecret) .Values.webmail.sessionSecret.value }}
  sessionSecret: {{ .Values.webmail.sessionSecret.value | quote }}
  {{- end }}
  {{- if and (not .Values.webmail.adminPassword.existingSecret) .Values.webmail.adminPassword.value }}
  adminPassword: {{ .Values.webmail.adminPassword.value | quote }}
  {{- end }}
  {{- if and .Values.webmail.oauth.enabled (not .Values.webmail.oauth.existingSecret) .Values.webmail.oauth.clientSecret }}
  oauthClientSecret: {{ .Values.webmail.oauth.clientSecret | quote }}
  {{- end }}
{{- end }}
