{{- if and .Values.webmail.enabled .Values.webmail.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stalwart.webmailServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" (merge (dict "app.kubernetes.io/component" "webmail") (omit .Values.webmail.additionalLabels "app.kubernetes.io/name" "app.kubernetes.io/instance" "app.kubernetes.io/component")) "context" .) | nindent 4 }}
  annotations:
    {{- include "stalwart.webmailAnnotations" (dict "specific" .Values.webmail.serviceAccount.annotations "context" .) | nindent 4 }}
automountServiceAccountToken: {{ .Values.webmail.serviceAccount.automountServiceAccountToken }}
{{- end }}
